version: '3'

services:
  vitalam-node:
    image: ghcr.io/digicatapult/vitalam-node:v2.3.0
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    environment:
      - IDENTITY=dev
      - WS=true
      - RPC=true
      - CORS=all
    restart: on-failure
