apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-identity-service.fullname" . }}-config
  labels:
    {{- include "vitalam-identity-service.labels" . | nindent 4 }}
data:
  apiHost: {{ .Values.config.apiHost }}
  apiPort: {{ .Values.config.dbPort | quote }}
  logLevel: {{ .Values.config.logLevel }}
  dbHost: {{ include "vitalam-identity-service.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
  authJwksUri: {{ .Values.config.authJwksUri | quote }}
  authAudience: {{ .Values.config.authAudience | quote }}
  authIssuer: {{ .Values.config.authIssuer | quote }}
  authTokenUrl: {{ .Values.config.authTokenUrl | quote }}
