apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vitalam-identity-service.fullname" . }}
  labels:
    {{- include "vitalam-identity-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "vitalam-identity-service.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        name: {{ include "vitalam-identity-service.fullname" . }}
    spec:
      {{- include "vitalam-identity-service.imagePullSecrets" . | indent 6 }}
      initContainers:
        - name: {{ include "vitalam-identity-service.initDb.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: [ 'npx', 'knex', "migrate:latest", "--env", "production" ]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-secret
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-secret
                  key: dbPassword

      containers:
        - name: {{ include "vitalam-identity-service.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-secret
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vitalam-identity-service.fullname" . }}-secret
                  key: dbPassword
