apiVersion: v2
name: vitalam-identity-service
appVersion: '0.0.2'
description: A Helm chart for vitalam-identity-service
version: '0.0.2'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
dependencies:
  - name: postgresql
    version: '^10.12.2'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
