postgresql:
  enabled: true
  postgresqlDatabase: vitalam
  postgresqlUsername: postgres
  postgresqlPassword: postgres
config:
  port: 80
  logLevel: info
  dbName: vitalam
  dbPort: 5432
image:
  repository: ghcr.io/digicatapult/vitalam-identity-service
  pullPolicy: IfNotPresent
  tag: 'v0.0.1'
  pullSecrets: ['ghcr-digicatapult']
